Repository informalsystems/atomkraft, pull requests merged in 2022-08, with the labels that each got.

#95 Streamlining the transfer tutorial
  examples/cosmos-sdk/transfer/transfer.md
  examples/cosmos-sdk/transfer/transfer.tla
  pyproject.toml
Labels: documentation

#104 Fix copying after test execution
  atomkraft/test/trace.py
Labels: bug

#108 Abort Atomkraft CLI if run outside of a project
  atomkraft/cli/__init__.py
  atomkraft/utils/project.py
Labels: bug

#114 Hide exception traceback
  .github/workflows/python.yml
  atomkraft/cli/__init__.py
Labels: enhancement
