Repository informalsystems/atomkraft, pull requests merged in 2022-11, with the labels that each got.

#165 Replace `block` mode with `sync` when tx broadcasting
  atomkraft/chain/testnet.py
Labels: bug

#182 fix: wait for grpc endpoints
  atomkraft/chain/node.py
  atomkraft/chain/testnet.py
  poetry.lock
  pyproject.toml
Labels: bug

#183 fix: ignore `Tx` events if filter is unset
  atomkraft/chain/utils.py
Labels: bug

#175 refactor: combine multiple trace tests into single file
  atomkraft/test/model.py
  atomkraft/test/test.py
  atomkraft/test/trace.py
  atomkraft/utils/filesystem.py
  atomkraft/utils/helpers.py
  tests/cli/test_transfer.md
Labels: enhancement

#188 test(cli): add verbosity for failing tests
  tests/cli/test_transfer.md
Labels: bug

#178 docs(tutorial): update `transfer` tutorial
  README.md
  atomkraft/model/traces.py
  examples/cosmos-sdk/transfer/reactor.py
  examples/cosmos-sdk/transfer/transfer.md
  examples/cosmos-sdk/transfer/transfer.tla
  poetry.lock
  pyproject.toml
  template/chain.toml
  tests/cli/test_transfer.md
Labels: user support

#186 fix: dynamic json parsing of process output
  .github/workflows/cli.yml
  .github/workflows/e2e.yml
  .github/workflows/python.yml
  atomkraft/chain/node.py
Labels: bug

#185 fix: use correct coin type
  atomkraft/chain/node.py
  atomkraft/chain/testnet.py
Labels: bug

#181 refactor(cli): use `jinja` over `copier`
  atomkraft/cli/__init__.py
  atomkraft/templates/project/.atomkraft/config.toml
  atomkraft/templates/project/.atomkraft/smoke_tests/.gitkeep
  atomkraft/templates/project/.modelator/.gitkeep
  atomkraft/templates/project/atomkraft.toml
  atomkraft/templates/project/chain.toml
  atomkraft/templates/project/model.toml
  atomkraft/templates/project/models/.gitkeep
  atomkraft/templates/project/pyproject.toml
  atomkraft/templates/project/pytest.ini
  atomkraft/templates/project/reactors/.gitkeep
  atomkraft/templates/project/reports/.gitkeep
  atomkraft/templates/project/tests/.gitkeep
  atomkraft/templates/project/traces/.gitkeep
  atomkraft/utils/project.py
  copier.yml
  poetry.lock
  pyproject.toml
  template/.atomkraft/smoke_tests/test_cosmwasm.py
  tests/cli/docker_entrypoint.sh
  tests/cli/test_transfer.md
Labels: enhancement

#197 docs: small updates to the installation steps
  INSTALLATION.md
Labels: user support

#199 fix: location of report files
  atomkraft/test/test.py
Labels: bug
